# Generated by Django 5.0.2 on 2024-02-09 21:08

import random

from django.db import migrations
from faker import Faker


def generate_fake_data(apps, schema_editor):
    Faker.seed(4321)
    fake = Faker()

    Artist = apps.get_model("music", "Artist")
    Album = apps.get_model("music", "Album")
    Song = apps.get_model("music", "Song")

    artists = []
    for _ in range(50):  # Generate 10 artists
        artist = Artist(name=fake.name(), bio=fake.text())
        artist.save()
        artists.append(artist)

    for artist in artists:
        for _ in range(random.randint(1, 10)):
            album = Album(
                artist=artist,
                title=fake.sentence(),
                release_date=fake.date(),
                genre=fake.word(),
            )
            album.save()

            for _ in range(random.randint(5, 15)):
                Song(
                    album=album,
                    title=fake.sentence(),
                    duration=random.randint(120, 360),
                    lyrics=fake.text(),
                ).save()


class Migration(migrations.Migration):
    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(generate_fake_data),
    ]
